FROM python:3.11

WORKDIR /tests

COPY pyproject.toml poetry.lock .

RUN pip install --no-cache-dir poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-root --no-interaction --no-cache && \
    rm -rf /root/.cache

COPY tests .

CMD ["pytest", "-v"]
