[tasks."deps:install"]
run = "poetry install --no-root"

[tasks."deps:add"]
args = ["dependency"]
run = "poetry add $dependency"

[tasks."deps:add-dev"]
args = ["dependency"]
run = "poetry add --group=dev $dependency"


[tasks."serve:dev"]
run = "poetry run uvicorn temporal_retriever.app:app --host 0.0.0.0 --port 8000 --reload"

[tasks."docker:build"]
run = """
  POETRY_VERSION=$(poetry version -s)
  echo "Using $POETRY_VERSION"

  DOCKER_IMAGE="hyperprior/temporal-retriever"
  docker build -t "$DOCKER_IMAGE:$POETRY_VERSION" -t "$DOCKER_IMAGE:latest" .
"""

[tasks."docker:push"]
depends = ["docker:build"]
run = """
  POETRY_VERSION=$(poetry version -s)

  DOCKER_IMAGE="hyperprior/temporal-retriever"
  docker push "$DOCKER_IMAGE:$POETRY_VERSION"
  docker push "$DOCKER_IMAGE:latest"
"""

[tasks."docker:run"]
depends = ["docker:build"]
run = "docker run -p 8000:8000 hyperprior/temporal-retriever:latest"


[tasks."git:rebase"]
run = "git pull --rebase"

[tasks."git:push"]
description = "interactively push changes to git"
run = """
  git add .
  git commit
  git push
"""

[tasks."update:patch"]
description = "push changes to github, tag current version to docker and push, patch update version"
run = """
  poetry version patch
  poetry update
"""

[tasks."update:minor"]
description = "push changes to github, tag current version to docker and push, minor update version"
run = """
  poetry version minor
  poetry update
"""



[tasks."test:unit"]
description = "unit tests"
run = "poetry run pytest -vvv"

[tasks."synthesize"]
run = "poetry run python -m synthesize_data"


[tasks.notebook]
run = "poetry run jupyter lab"

[tasks."test:integration"]
depends = ["docker:build"]
run = """
container_id=$(docker run -d -p 8080:8080 hyperprior/temporal-retriever:latest)

# Wait for the container to start
sleep 5

until $(curl --output /dev/null --silent --head --fail http://localhost:8080/health); do
    printf '.'
    sleep 5
done

echo "running tests in container=${container_id}"

collection_id=$(skate get temporal-retriever-collection-id@postman)
env_id=$(skate get temporal-retriever-collection-env@postman)
echo "using collection ${collection_id}"
echo "using collection env ${env_id}"

postman collection run $collection_id -e $env_id

exit_code=$?

docker kill $container_id

docker rm $container_id
exit $exit_code
"""
